### ISSUE TITLE
Owl-carousel with reactive list

### ISSUE THREAD

**Issue by KudMath** [markoshust/meteor-owl-carousel-2#1]
Hi, i'm trying to implement owl carousel in meteor and passing it a reactive list of images seems to break it (image get displayed on top of one another). Any idea?

**Comment by midisale** [comment]
Same problem here.

**Comment by artcab** [comment]
Same here

**Comment by artcab** [comment]
So I fixed it by calling the initialization code in the subscriptions callback, it works even after adding stuff to the collection :smiley: 

`Template.<template name>.onCreated(function OnCreated() {`
 `Meteor.subscribe('<your subscription>', function(){`
  `$('.owl-carousel').owlCarousel({});`
 `});`
`});`

**Comment by naho2081** [comment]
Had same issue.
Fixed by adding setTimeout.

`Meteor.setTimeout (->`
        `$(".owlCarousel").owlCarousel`
        `items: 3`
        `dots: false`
        `loop: true`
        `nav: true`
        `navText: ''`
    `), 0`
